package blockchain.entrepreneur.cuisine.model.Classification;

public enum CategoriesIngredient {
	LEGUMES,LEGUMINEUSES,FRUITS,OLEAGINEUX,FECULENTS,VIANDES,VEGETAL,POISSONS,OEUFS,LAITS,BOISSONS,ALCOOL,SUCRES,BISCUITS,GLACES,HUILES,SAUCES,CONDIMENTS,EPICES,DIVERS
}
